BoothGroup/Vayesta

.github/workflows/ci.yaml
vayesta/rpa/rirpa/RIRPA.py

Fixes the RIRPA docstring and runs it through a reformatter.

Fix RIRPA docstring and reformat code.

---

setup.py

Should fix #29:
- Changes `setup.py` to include tests in package directory
- Adds missing `__init__.py` to `solver/eb_fci`

Package installation fixes

---

vayesta/core/fragmentation/cas.py
vayesta/rpa/rirpa/NI_eval.py
vayesta/rpa/rirpa/RIRPA.py
vayesta/tests/ewf/test_molecules.py

Quick update to CAS fragmentation functionality, with a minor tweak to RIRPA as well.
This adds reporting of the occupied and virtual energy gaps when adding a fragment, and covers a few more edge cases related to these quantities to ensure degenerate orbitals aren't being split in the cas.
While doing this, I updated us to be consistent with `pyscf`'s CAS specification, so we have
```
with emb.cas_fragmentation() as f:
f.add_cas_fragment(ncas, nelec)
```
rather than swapping the inputs.
Finally, I had another look at occasional floating-point overflow errors in the RIRPA, which @maxnus originally flagged and I thought were mislabelled underflow errors.
Making changes to ensure suppression of those errors didn't solve the problem, so I had a closer look and managed to identify that very …

CAS update+RIRPA floating point overflows

---

vayesta/core/ao2mo/helper.py
vayesta/core/fragmentation/cas.py
vayesta/dmet/__init__.py
vayesta/edmet/__init__.py
vayesta/ewf/__init__.py
vayesta/rpa/rirpa/NI_eval.py
vayesta/rpa/rirpa/RIRPA.py
vayesta/tests/common.py
vayesta/tests/core/ao2mo/test_postscf_ao2mo.py
vayesta/tests/ewf/test_h2_pbc.py
vayesta/tests/ewf/test_molecules.py
vayesta/tests/misc/test_molstructs.py
vayesta/tests/testsystems.py

Contraction of vvVV block with eris when nvira xor nvirb is zero, fails.
Added check to skip that contribution when necessary.

Fix bug in UHF 2dm cumulant 

---

vayesta/core/qemb/fragment.py
vayesta/core/qemb/qemb.py

Allows setting bath options specific to the occupied or virtual bath only, e.g.
`bath_options(bathtype_occ='full', bathtype_vir='mp2')`.

Adds support for occ-type specific bath options

---

vayesta/core/bath/bath.py
vayesta/core/bath/bno.py
vayesta/core/fragmentation/fragmentation.py
vayesta/core/qemb/fragment.py
vayesta/core/spinalg.py
vayesta/ewf/ewf.py
vayesta/ewf/fragment.py
vayesta/ewf/icmp2.py
vayesta/tests/ewf/test_fbc.py

This add a finite bath (energy) correction ("FBC"), which can be calculated using `ewf.get_fbc_energy()`.
The correction is calculated from the subspace MP2 calculations independently for the finite occupied and finite virtual bath, as described in my PhD thesis. It can be combined with the secondary fragment ("delta-MP2") correction.
The cost of the calculation is dominated by N^3 per fragment integral transformation, which is the same cost as the integral transformation needed for each BNO bath (storing these integrals would be a possibility, but would likely require too much memory ni most scenarios).  
The correction can in principle be also added to the DM-energy, in the sense that the limits are correct and the contributions are in principle not overcounting anything.

BNO finite bath correction

---

examples/ewf/molecules/01-simple-ccsd.py
vayesta/solver/ccsd.py
vayesta/solver/cisd.py
vayesta/tests/dmet/test_molecule.py

This adds CISD as an initial guess for the CCSD solver.
Syntax:
`solver_options=dict(init_guess='CISD')`

Adds CISD initial guess for CCSD

---

vayesta/core/qemb/qemb.py
vayesta/ewf/fragment.py
vayesta/solver/fci.py
vayesta/tests/ewf/test_tailoring.py
vayesta/tests/testsystems.py

PySCF's `fix_spin_` decorator for FCI seems to produce non-deterministic results when used with UHF orbitals.

Adds tailoring tests, deactivates fix_spin for UFCI

---

.github/workflows/ci.yaml

Currently the nightly test also publishes docs which is unnecessary and spams everybody's github feed. This excludes the deployment of docs from scheduled actions.

Disable doc build for scheduled runs

---

vayesta/tests/core/qemb/test_fragment.py

The `project_ref_orbitals` test has been failing since a recent numpy update. I am pretty sure this was just a badly conditioned test. Just disabling it for now so that the nightly CI stops failing.

Disables test

---

vayesta/core/types/wf/fci.py
vayesta/solver/fci.py
vayesta/tests/ewf/test_h2.py
vayesta/tests/testsystems.py

For a system which has strong AFM character running the default single-site EWF calculation in Vayesta with a spin-symmetry broken reference results in an error due to CISD coefficient generation on master. Here's is a minimal example using a dissociated hydrogen molecule, but I originally came across it in H-ring dissociations and I'd expect the same for the high-U Hubbard model.
```import vayesta.ewf
from pyscf import gto, scf
from vayesta.misc.molecules import ring
mol = gto.M()
mol.atom = "H  0  0  0;  H  0  0  10.0"
mol.basis="sto-3g"
mol.build()
umf = scf.UHF(mol).density_fit()
umf.kernel()
umf.kernel(dm0=umf.make_rdm1(mo_coeff=umf.stability()[0]))
uewf = vayesta.ewf.EWF(umf, solver="FCI", bath_options={"bathtype":"dmet"})
uewf.kernel()
```
from which I get the error
```
Traceback …
```

Fix afm single site

---

.github/workflows/ci.yaml

Updates `ci.yaml` to triggers tests to run for all PRs, not just for those to `master` or `dev`.
If this doesn't work to target all PRs we could explicitly filter for all branches within `pull_request`, but that seems unnecessary if this removes filtering entirely.

Run tests for PRs to all branches.

---

vayesta/lattmod/latt.py
vayesta/tests/edmet/test_dfedmet_hubbard.py
vayesta/tests/edmet/test_edmet_hubbard.py
vayesta/tests/ewf/test_hubbard.py
vayesta/tests/testsystems.py

This allows UHF calculations to be run on the 1D Hubbard model, where previously this resulting in an error when generating the initial guess density.
This also updates various aspects of testing for Hubbard models while I was in there. Specifically
- Added test confirming unrestricted EWF calculation without spin-symmetry breaking on the 1D Hubbard model returns the same result as an equivalent restricted calculation.
- `TestLattice.uhf()` will now correctly return a `LatticeUHF` object.
- Reintroduced EDMET tests previously suspended due to #9, while also updating most tests in the same files to the new translational symmetry notation.

UHF on the 1D Hubbard model

---

vayesta/tests/ewf/test_h2.py
vayesta/tests/testsystems.py

This fixes the test failures on #69, as discussed in #83, by changing the test to use dense ERIs rather than density fitting. Breaking spin symmetry here required a more explicitly symmetry-broken initial guess than with density fitting, so I've added the suggested approach to break symmetries from `pyscf/examples/scf/32-break_spin_symm.py` into `TestMolecule.uhf_stable`.
This doesn't fix using density fitting in this system- that's proved more difficult (see #84, which I'm going to close now), but given it's an edge case this seems acceptable for now. I would say we could just add a warning/error if a cluster has no excitations in a spin channel and is using density fitting, but this is going to come up again if we're running large Hubbard models.
For now this passes the tests in the …

Fix dissociated H2 test.

---

vayesta/solver/fci.py
vayesta/tests/dmet/test_molecule.py
vayesta/tests/ewf/test_molecules.py

This fixes the control of initial guesses within the FCI solver, which I came across in the process of trying to fix #84.
I would suggest we merge this after #69 for simplicity; it's not anything high priority.
8502952ee77304ba9141ead8369b36af03d497c9 added the function
```
def get_init_guess(self):
if self.opts.init_guess is None:
return dict(ci0=None)
if self.opts.init_guess == 'CISD':
self.log.info("Generating intitial guess from CISD.")
return dict(ci0=self.get_cisd_init_guess())
raise ValueError
```
to control the generation of initial guesses for FCI wavefunctions. This seems to have intended passing `solver_opts={"init_guess":None}` to result in an initial guess of the HF determinant, rather than the CISD wavefunction. However, due to inheritance within the code interpreting `None` …

Fix fci init_guess

---

vayesta/core/qemb/qemb.py
vayesta/tests/core/scmf/test_scmf.py

This implements the changes suggested in #91 to avoid test failures when running python 3.11, while also reactivating the pDMET test and updating it so it passes (in my running). This doesn't update any configuration options etc as I think we can do that all in one place- which is #97 or a follow-up to it.
This is entirely self-contained and shouldn't affect any outstanding PRs.

Fix SCMF/python 3.11 support

---

vayesta/core/qemb/scrcoulomb.py
vayesta/core/types/wf/fci.py
vayesta/solver/fci.py
vayesta/solver/hamiltonian.py
vayesta/tests/core/wf/test_wf.py
vayesta/tests/testsystems.py

This updates the UFCI solver to support clusters with different numbers of orbitals within the alpha and beta spin channels. This makes use of the dummy orbital construction contained within #92. However, implementation was complicated by the fact that neither pyscf's FCI and CASCI functionality support having different numbers of active orbitals in different spin channels, and that we use the associated FCI functions as a backend when calculating wavefunction properties within `UFCI_WaveFunction`.
To get around this, this PR implements an object `UFCI_WaveFunction_w_dummy` which represents a UFCI wavefunction with differing numbers of orbitals in the different spin channels via the wavefunction padded with dummy orbitals. These dummy orbitals are traced out of any expectation values …

UFCI different norbs in spin channels

---

vayesta/core/qemb/corrfunc.py
vayesta/core/qemb/qemb.py

This adds the options to generate correlation functions using a IAO fragmentation and for specific target orbitals within the corrfunc functionality of the embedding methods. This allows correlation functions to be calculated in specific local orbital spaces on each atom, rather than the full local hilbert space.

Corrfunc orb filtering

---

examples/ewf/solids/01-simple-sym.py
vayesta/core/fragmentation/iao.py

This relates to the errors mentioned in #106.
This returns a more informative error message when encountering a bug with generating IAOs in pyscf with space group symmetry enabled. This should only be present in a small number of pyscf versions, so requiring the user to update their input rather than trying to handle it internally seems a reasonable. The fix is to just disable space group symmetry for the mean-field calculation when initialising the IAO fragmentation; it can be turned back on afterwards if desired.

Added informative error message when encountering pyscf space_group_symmetry bug.

---

pyproject.toml

This PR temporarily freezes the SciPy version, as 1.11.0 seems to break both cvxpy and PySCF.

Force SciPy <= 1.10.0

---

MANIFEST.in

The `logo.txt` didn't appear in `MANIFEST.in`, so it wasn't part of the package. Somehow this is only an issue when a test failed on the scheduled CI

Add logo.txt to MANIFEST.in

---

pyproject.toml

`ebcc` is now available as a `pip` wheel, this PR changes the dependency to reflect that.

Changes ebcc dependency to pip wheel

---

vayesta/misc/variational_embedding/calc_nonorth_couplings.py

This makes a few changes to wick.wick_orbitals calls in calc_nonorth_couplings to update the code accordingly for the changes in pygnme. the pygnme pr can be merged after this

updated the ci no couplings for pygnme update, and unequal active spaces

---

vayesta/tests/ewf/test_h2_pbc.py

This updates the hard coded energy values for EWF calculations with a truncated bath to maintain compatibility with the latest version of pyscf (2.3).
It would be possible to also support older versions but I don't think that will be sustainable in the long run.

Update 2D PBC ref values for finite bath

---

examples/ewf/molecules/26-ebCC-solvers.py
examples/ewf/molecules/26-ebcc-solvers.py
vayesta/core/qemb/qemb.py
vayesta/core/types/wf/ccsd.py
vayesta/core/types/wf/project.py
vayesta/core/types/wf/wf.py
vayesta/ewf/ewf.py
vayesta/ewf/fragment.py
vayesta/ewf/ufragment.py
vayesta/solver/__init__.py
vayesta/solver/ebcc.py
vayesta/solver/hamiltonian.py
vayesta/tests/core/scmf/test_scmf.py
vayesta/tests/solver/test_ebcc.py
vayesta/tests/testsystems.py

Updates the Vayesta interface for solvers from `ebcc`, adding support for CCSDt' active space solvers. Notable background updates are:
- Added functionality to apply rotations to CCSD wavefunctions and run solver calculations in a rotation of the cluster basis.
- Fixed factor of two conversion between certain spin components  of UCCSD T2 amplitudes from `ebcc`.
- Added tests and examples for using solvers from `ebcc` (CCSD, CCSDT and CCSDt').

CCSDt' interface (and general EBCC interface updates)

---

.github/workflows/ci.yaml

This attempts to install Vayesta in editable mode within the github CI. This should hopefully fix the codecov (no guarantees) since we seem to actually be encountering a bug with `coverage.py` itself; for more info see https://github.com/nedbat/coveragepy/issues/1034 or https://stackoverflow.com/questions/72986258/pytest-cov-showing-no-coverage.
It seems like the issue is that since we're installing not in editable mode, we're not technically running the `/vayesta` repository we specify we want coverage for and so no activity is traced. With any luck being in editable mode fixes this, otherwise I'll investigate something else.
Looking at the coverage bot this started after merging https://github.com/BoothGroup/Vayesta/pull/97 and moving from `setup.py` to `pyproject.toml`, so I guess that …

CodeCov Fix Attempt

---

codecov.yml

This adds an additional codecov target which should fail if a PR reduces test coverage by more than 0.5%. This is arbitrarily configurable, but this seemed like a level of reduction which should allow large PRs with partial test coverage while prompting consideration if tests are totally absent.
This follows on from #123 , which fixed an issue with coverage calculation introduced in #97 that would've been caught by a check like this.

Add codecov limit on coverage reduction.

---

.github/workflows/run_tests.py
pyproject.toml
vayesta/core/qemb/qemb.py
vayesta/core/types/__init__.py
vayesta/core/types/ebwf/__init__.py
vayesta/core/types/ebwf/ebcc.py
vayesta/core/types/ebwf/ebccsd.py
vayesta/core/types/ebwf/ebwf.py
vayesta/core/types/wf/project.py
vayesta/edmet/fragment.py
vayesta/ewf/ewf.py
vayesta/solver/ebcc.py
vayesta/solver/ebfci.py
vayesta/solver/hamiltonian.py
vayesta/tests/core/wf/test_ebcc_wf.py
vayesta/tests/solver/test_ebcc.py

This adds CC wavefunction objects which use `ebcc` as a backend, rather than `pyscf`, along with tests for this functionality.  With this we'll have a bit more flexibility in our wavefunction specifications, as it's compatible with arbitrary CC ansatzes. This is a prerequisite to making more use of coupled electron-boson clusters.
I've also included a small tweak to the `pyproject.toml` which allows tests tagged veryslow to be run; previously our configuration was actually blocking running these tests, even when requested.

ebcc wavefunctions

---

vayesta/core/scmf/brueckner.py

Addressing #132, but was not able to run the attached example to verify

Fixes #132

---

vayesta/core/scmf/brueckner.py
vayesta/core/scmf/pdmet.py
vayesta/core/scmf/scmf.py

This is to reduce code duplication in the UHF versions of SCMF, which now calls the RHF update twice.
Together with #133 this addresses #132 for the UHF case

Refactors SCMF UHF code

---

vayesta/core/qemb/qemb.py

In reference to https://github.com/BoothGroup/Vayesta/issues/132#issuecomment-1729284251

Reduces bath_options.occupation_tolerance to 1e-6

---

.github/workflows/ci.yaml
examples/ewf/molecules/26-ebcc-solvers.py
vayesta/core/qemb/qemb.py
vayesta/ewf/fragment.py
vayesta/solver/ebcc.py
vayesta/solver/hamiltonian.py
vayesta/tests/solver/test_ebcc.py

Added Active space support for EBCC CCSDt; Avoid considering auxiliary for orthogonality tests for EC-CC or TCC calculations. Changes in hamiltonian.py to return a np array of (2, modim, modim) instead of a tuple, the tuple results in errors in ebcc for UHF. PYSCF-wide default is the np array.

Some changes to facilitate newly implemented CCSDt

---

examples/ewdmet/65-callback-solver-dyson.py
examples/ewf/molecules/65-callback-solver.py
vayesta/ewf/ewf.py

Fixes issue when providing only the DMs from a callback solver in an SCMF calculation.
Adds example showing how to use dyson to return spectral moments from a callback solver.

Add callback solver example using dyson for EWDMET

---

pyproject.toml
vayesta/core/qemb/qemb.py
vayesta/dmet/__init__.py
vayesta/edmet/__init__.py
vayesta/ewf/__init__.py
vayesta/lattmod/latt.py
vayesta/tests/core/qemb/test_integrals.py
vayesta/tests/rpa/test_rirpa_solids.py

Some changes to maintain compatibility with the latest pyscf.

Testing with latest pyscf

---

vayesta/solver/callback.py

The `converged` property on the fragments results from a callback solver were not properly set. This fixes it and sets the property to the value present in the callback results, if present.

Set fragment converged property from callback results

---

vayesta/solver/hamiltonian.py

The definition of the output on the cluster `mol` object didn't support setting it to a particular path. This meant that the output file from the cluster `mol` object was always stored in the current working directory, rather than where the output file of the main mean-field `mol` object was set to. This pull request fixes it, so that all PySCF output files are now stored in the same user defined directory.

Add support for directories in cluster mol output

---

pyproject.toml

Freezes the `ebcc` version until #182 is addressed

Freeze `ebcc` to 1.5.0

---

vayesta/core/types/wf/fci.py
vayesta/ewf/ufragment.py

Resolves a number of issues due to padding and zero virtual orbitals in a cluster.

Fix issues due to zero virtual orbitals in a cluster

---

examples/ewf/molecules/64-callback-solver-dms.py
examples/ewf/molecules/66-callback-solver-dms-uhf.py
vayesta/core/scmf/pdmet.py
vayesta/ewf/ewf.py

Attempts to calculate WF RDM when using callback solver. If this fails, falls back to democratically partitioned RDM.
Fixes issue when combining p-DMET with a callback solver.

Calculate relevant RDM when using callback solver

---

vayesta/core/types/ebwf/ebcc.py

Fixes `ebcc` interface for `ebcc>1.5.0`
There are still some test failures -- most are a missing `_get_amps` method, this is not something that I have touched? and a regularly failing test.

Fix `ebcc` interface

---

.github/workflows/ci.yaml
pyproject.toml
vayesta/core/bath/rpa.py
vayesta/core/helper.py
vayesta/core/symmetry/operation.py
vayesta/core/symmetry/tsymmetry.py
vayesta/core/types/ebwf/ebcc.py
vayesta/dmet/updates.py
vayesta/mpi/rma.py
vayesta/solver/ebcc.py
vayesta/tests/edmet/test_dfedmet_molecule.py
vayesta/tests/latt/test_bethe.py
vayesta/tests/solver/test_ebcc.py
vayesta/tools/plotting/plotly_mol.py

- Adds openblas installation to CI workflow.
- Removes CI for python 3.8
- Adds CI for python 3.12 and 3.13
- Adds scipy>=1.11.0 and h5py>=3.0.0 version constraints for EBCC compatibility

Fix CI, remove python 3.8 add 3.12, 3.13

---

vayesta/tests/core/qemb/test_fragment.py
vayesta/tests/core/test_foldscf.py
vayesta/tests/testsystems.py

Pyscf has updated the default DF basis selection. Need to specify a DF basis for 631g Helium.

Specify DF basis for helium for pyscf compatibility
